const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={device:null,data:null,session:localStorage.getItem('sparkle_session')||'',filter:'all',eventCursor:0};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2800)}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};const r=await fetch(path,{...opts,headers,credentials:'same-origin'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function showPair(){document.body.classList.remove('ready');$('#pair-screen').classList.remove('hidden');$('#app').classList.add('hidden');$('#pair-os').value=navigator.platform||'Browser';}
function showApp(){document.body.classList.add('ready');$('#pair-screen').classList.add('hidden');$('#app').classList.remove('hidden');}
function statusClass(status){return ['COMPLETED','ONLINE','ACTIVE'].includes(status)?'status':'status waiting'}
function timeText(value){if(!value)return '—';try{return new Intl.DateTimeFormat([], {dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return value}}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));const titles={home:['PERSONAL WORKSPACE','Home'],chat:['CONTINUOUS CONTEXT','Conversation'],tasks:['ORCHESTRATION','Tasks'],approvals:['HUMAN AUTHORITY','Approvals'],devices:['TRUST BOUNDARY','Devices'],notifications:['ATTENTION','Notifications'],artifacts:['VERIFIED OUTPUTS','Artifacts']};$('#view-eyebrow').textContent=titles[name][0];$('#view-title').textContent=titles[name][1];$('.sidebar').classList.remove('open');if(name==='chat')loadMessages();}
function miniEmpty(text){return `<p class="muted">${esc(text)}</p>`}
function renderTaskCard(t){return `<article class="task-card"><div class="row"><div><div class="status">${esc(t.status)}</div><h3>${esc(t.goal||'Background task')}</h3></div><strong>${Number(t.progress)||0}%</strong></div><p class="muted">${esc(t.current_operation?`Current: ${t.current_operation}`:'No active operation')}</p><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(t.progress)||0))}%"></span></div></article>`}
function renderHome(){const tasks=(state.data?.tasks||[]).filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).slice(0,3);$('#active-work').innerHTML=tasks.length?tasks.map(renderTaskCard).join(''):miniEmpty('No active tasks. Ask SPARKLE to start something.');const approvals=state.data?.pending_approvals||[];$('#home-approvals').innerHTML=approvals.length?approvals.slice(0,3).map(a=>`<div class="mini-row"><span>${esc(a.action)}</span><b>${esc(a.risk)}</b></div>`).join(''):miniEmpty('Nothing is waiting for approval.');const devices=state.data?.devices||[];$('#home-devices').innerHTML=devices.length?devices.slice(0,4).map(d=>`<div class="mini-row"><span>${esc(d.name)}</span><span class="status">${esc(d.status)}</span></div>`).join(''):miniEmpty('No devices registered.');const notes=(state.data?.notifications||[]).slice(-4).reverse();$('#home-notifications').innerHTML=notes.length?notes.map(n=>`<div class="mini-row"><span><b>${esc(n.title)}</b><br><small class="muted">${esc(n.body)}</small></span><span>${esc(n.priority)}</span></div>`).join(''):miniEmpty('No recent notifications.');}
function renderTasks(){const all=state.data?.tasks||[];const filtered=all.filter(t=>state.filter==='all'||(state.filter==='active'&&!['COMPLETED','CANCELLED','FAILED','BLOCKED'].includes(t.status))||(state.filter==='waiting'&&['WAITING','BLOCKED'].includes(t.status))||(state.filter==='complete'&&t.status==='COMPLETED'));$('#task-list').innerHTML=filtered.length?filtered.map(t=>`<article class="list-card"><div class="head"><div><span class="${statusClass(t.status)}">${esc(t.status)}</span><h3>${esc(t.goal||t.goal_id)}</h3><p class="muted">Started ${esc(timeText(t.started))} · ${esc(t.current_operation||'No active step')}</p></div><strong>${Number(t.progress)||0}%</strong></div><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(t.progress)||0))}%"></span></div><div class="actions">${!['COMPLETED','CANCELLED'].includes(t.status)?`<button class="action" data-background="${esc(t.goal_id)}">Background</button><button class="action" data-task="resume" data-id="${esc(t.goal_id)}">Resume</button><button class="action" data-task="replan" data-id="${esc(t.goal_id)}">Replan</button><button class="action danger" data-task="cancel" data-id="${esc(t.goal_id)}">Cancel</button>`:''}</div></article>`).join(''):miniEmpty('No tasks in this view.');}
function renderApprovals(){const rows=state.data?.pending_approvals||[];$('#approval-list').innerHTML=rows.length?rows.map(a=>`<article class="list-card"><div class="head"><div><span class="status">${esc(a.risk)} RISK</span><h3>${esc(a.action)}</h3><p class="muted">Capability: ${esc(a.capability)} · Scope: ${esc(a.requested_scope)}<br>Requested ${esc(timeText(a.requested_at))}${a.expires_at?` · Expires ${esc(timeText(a.expires_at))}`:''}</p></div></div><div class="actions"><button class="action approve" data-approval="approve" data-id="${esc(a.approval_id)}">Approve</button><button class="action reject" data-approval="reject" data-id="${esc(a.approval_id)}">Reject</button></div></article>`).join(''):miniEmpty('No pending approvals.');}
function renderDevices(){const rows=state.data?.devices||[];$('#device-list').innerHTML=rows.length?rows.map(d=>`<article class="device-card"><div class="device-icon">${d.kind==='phone'?'▯':d.kind==='tablet'?'▭':'⌁'}</div><h3>${esc(d.name)}</h3><p><span class="${statusClass(d.status)}">${esc(d.status)}</span> · ${esc(d.kind)} · ${esc(d.os_name)}</p><p class="muted">Last seen ${esc(timeText(d.last_seen))}</p><div class="capabilities">${(d.capabilities||[]).map(c=>`<span class="cap">${esc(c)}</span>`).join('')}</div><div class="actions"><button class="action" data-device-rename="${esc(d.device_id)}">Rename</button>${state.device?.device_id!==d.device_id?`<button class="action danger" data-device-revoke="${esc(d.device_id)}">Revoke</button>`:''}</div></article>`).join(''):miniEmpty('No authorized devices.');}
function renderArtifacts(){const rows=[...(state.data?.artifacts||[])];$('#artifact-list').innerHTML=rows.length?rows.map(a=>`<article class="list-card"><div class="head"><div><span class="status">${esc(a.status)}</span><h3>${esc(a.project_name)}</h3><p class="muted">${esc(a.artifact_name)} · ${Number(a.artifact_bytes||0).toLocaleString()} bytes<br>SHA-256 ${esc(String(a.artifact_sha256||'').slice(0,16))}… · ${esc(timeText(a.created_at))}</p></div></div><div class="actions"><a class="action" href="/api/artifacts/${encodeURIComponent(a.artifact_id)}/download">Download verified package</a></div></article>`).join(''):miniEmpty('No generated artifacts yet.');}
function renderNotifications(){const rows=[...(state.data?.notifications||[])].reverse();$('#notification-list').innerHTML=rows.length?rows.map(n=>`<article class="list-card"><div class="head"><div><span class="status">${esc(n.priority)}</span><h3>${esc(n.title)}</h3><p class="muted">${esc(n.body)}<br>${esc(timeText(n.created_at))}</p></div><span>${esc(n.status)}</span></div>${n.status==='UNREAD'?`<div class="actions"><button class="action" data-note-read="${esc(n.notification_id)}">Mark read</button></div>`:''}</article>`).join(''):miniEmpty('No notifications.');}
function renderSessions(){const picker=$('#session-picker');const rows=state.data?.sessions||[];picker.innerHTML=`<option value="">New conversation</option>`+rows.map(s=>`<option value="${esc(s.session_id)}" ${s.session_id===state.session?'selected':''}>${esc(s.active_goal_id?'Active conversation':'Conversation')} · ${esc(s.session_id.slice(0,8))}</option>`).join('');}
function renderBadges(){const a=(state.data?.pending_approvals||[]).length,n=(state.data?.notifications||[]).filter(x=>x.status==='UNREAD').length;[['#approval-badge',a],['#notification-badge',n]].forEach(([sel,v])=>{const e=$(sel);e.textContent=v;e.classList.toggle('hidden',!v)})}
async function refresh(){try{const data=await api('/api/state');const tasks=await api('/api/tasks');state.data={...data,tasks:tasks.tasks};state.device=(data.devices||[]).find(d=>d.status==='ONLINE'&&d.device_id===state.device?.device_id)||state.device;renderHome();renderTasks();renderApprovals();renderDevices();renderArtifacts();renderNotifications();renderSessions();renderBadges();if(state.data?.autonomy)$('#autonomy-mode').value=state.data.autonomy.mode;$('#core-status').textContent='Personal Core online';$('#device-pill').textContent=state.device?.name||'This device';}catch(e){if(/authentication|token|revoked/.test(e.message)){showPair();return}$('#core-status').textContent='Personal Core unavailable';toast(e.message)}}
async function loadMessages(){const box=$('#messages');if(!state.session){box.innerHTML=`<div class="message assistant">Hello. I’m SPARKLE. Start here and continue this same conversation from any authorized device.</div>`;return}try{const d=await api(`/api/sessions/${state.session}/messages`);box.innerHTML=d.messages.length?d.messages.map(m=>`<div class="message ${m.role}">${esc(m.text)}<div class="message-meta">${esc(timeText(m.created_at))}${m.status?` · ${esc(m.status)}`:''}</div></div>`).join(''):miniEmpty('No messages yet.');box.scrollTop=box.scrollHeight}catch(e){toast(e.message)}}
async function send(text){if(!text.trim())return;$('#activity').classList.remove('hidden');$('#activity-text').textContent='Planning and checking policy…';try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({text,session_id:state.session||null})});state.session=d.session_id;localStorage.setItem('sparkle_session',state.session);await refresh();setView('chat');await loadMessages();}finally{$('#activity').classList.add('hidden')}}
$('#pair-form').addEventListener('submit',async e=>{e.preventDefault();$('#pair-error').textContent='';try{const caps=['conversation','notifications','approvals','task_status','device_management','artifacts'];const d=await api('/api/enroll',{method:'POST',body:JSON.stringify({code:$('#pair-code').value.trim(),name:$('#pair-name').value.trim(),kind:$('#pair-kind').value,os:$('#pair-os').value.trim(),capabilities:caps,client:'web'})});state.device=d.device;showApp();await refresh()}catch(err){$('#pair-error').textContent=err.message}});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)});$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));$('#menu-button').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$('#refresh').addEventListener('click',refresh);
$('#hero-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('#hero-input'),text=input.value.trim();if(!text)return;input.value='';await send(text).catch(x=>toast(x.message))});$('#chat-form').addEventListener('submit',async e=>{e.preventDefault();const input=$('#chat-input'),text=input.value.trim();if(!text)return;input.value='';await send(text).catch(x=>toast(x.message))});
$('#session-picker').addEventListener('change',e=>{state.session=e.target.value;localStorage.setItem('sparkle_session',state.session);loadMessages()});$('#new-session').addEventListener('click',()=>{state.session='';localStorage.removeItem('sparkle_session');renderSessions();loadMessages()});
$('#task-list').addEventListener('click',async e=>{const bg=e.target.closest('[data-background]'),b=e.target.closest('[data-task]');try{if(bg){await api('/api/background',{method:'POST',body:JSON.stringify({goal_id:bg.dataset.background})});toast('Task queued for background execution');await refresh();return}if(!b)return;await api(`/api/tasks/${b.dataset.id}/${b.dataset.task}`,{method:'POST',body:'{}'});toast(`Task ${b.dataset.task} requested`);await refresh()}catch(x){toast(x.message)}});$('#approval-list').addEventListener('click',async e=>{const b=e.target.closest('[data-approval]');if(!b)return;try{await api(`/api/approvals/${b.dataset.id}/${b.dataset.approval}`,{method:'POST',body:'{}'});toast(`Approval ${b.dataset.approval}d`);await refresh()}catch(x){toast(x.message)}});$('#notification-list').addEventListener('click',async e=>{const b=e.target.closest('[data-note-read]');if(!b)return;try{await api(`/api/notifications/${b.dataset.noteRead}/read`,{method:'POST',body:'{}'});await refresh()}catch(x){toast(x.message)}});$('#device-list').addEventListener('click',async e=>{const revoke=e.target.closest('[data-device-revoke]'),rename=e.target.closest('[data-device-rename]');try{if(revoke){if(confirm('Revoke this device and invalidate its credentials?'))await api(`/api/devices/${revoke.dataset.deviceRevoke}/revoke`,{method:'POST',body:'{}'})}if(rename){const name=prompt('Device name');if(name)await api(`/api/devices/${rename.dataset.deviceRename}/rename`,{method:'POST',body:JSON.stringify({name})})}await refresh()}catch(x){toast(x.message)}});
$$('[data-task-filter]').forEach(b=>b.addEventListener('click',()=>{$$('[data-task-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.taskFilter;renderTasks()}));
$('#autonomy-mode').addEventListener('change',async e=>{try{await api('/api/settings/autonomy',{method:'POST',body:JSON.stringify({mode:e.target.value})});toast('Autonomy setting updated');await refresh()}catch(x){toast(x.message)}});
$('#forget-device').addEventListener('click',async()=>{if(confirm('Disconnect this browser from SPARKLE?')){try{await api('/api/logout',{method:'POST',body:'{}'})}catch{}localStorage.removeItem('sparkle_session');showPair()}});
function autosize(e){e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,150)+'px'};['#hero-input','#chat-input'].forEach(s=>$(s).addEventListener('input',autosize));
const h=new Date().getHours();$('#greeting').textContent=h<12?'GOOD MORNING':h<18?'GOOD AFTERNOON':'GOOD EVENING';
if('serviceWorker' in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{});
async function syncEvents(){if($('#app').classList.contains('hidden'))return;try{const d=await api(`/api/events?after=${state.eventCursor}&limit=100`);if(d.cursor)state.eventCursor=d.cursor;if(d.events?.length)await refresh()}catch{}}
(async()=>{showApp();try{await refresh();const e=await api('/api/events?limit=1');state.eventCursor=e.cursor||0}catch{showPair()}setInterval(syncEvents,1500);setInterval(()=>!$('#app').classList.contains('hidden')&&refresh(),15000)})();
